In [1]:
# # Mount Google Drive
# from google.colab import drive # import drive from google colab

# ROOT = "/content/drive"     # default location for the drive
# print(ROOT)                 # print content of ROOT (Optional)

# drive.mount("/content/drive")

/content/drive
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
# !pip install tokenizers==0.8.0-rc4

In [1]:
!pip install transformers==2.11.0
!pip install tensorboardx
!pip install simpletransformers==0.41.1

     |████████████████████████████████| 674 kB 516 kB/s eta 0:00:01
     |████████████████████████████████| 883 kB 595 kB/s eta 0:00:01
     |████████████████████████████████| 661 kB 453 kB/s eta 0:00:01
     |████████████████████████████████| 5.6 MB 33 kB/s eta 0:00:012     |███                             | 512 kB 2.0 MB/s eta 0:00:03
     |████████████████████████████████| 1.1 MB 55 kB/s  eta 0:00:01
  Created wheel for sacremoses: filename=sacremoses-0.0.43-py3-none-any.whl size=893259 sha256=0eda28dcf27b16b31dde42ba612bcbb50f67e116c9e3f450b935e0c07be651c2
  Stored in directory: /home/soham/.cache/pip/wheels/69/09/d1/bf058f7d6fa0ecba2ce7c66be3b8d012beb4bf61a6e0c101c0
Successfully built sacremoses
     |████████████████████████████████| 308 kB 339 kB/s eta 0:00:01
     |████████████████████████████████| 191 kB 361 kB/s eta 0:00:01


  Created wheel for seqeval: filename=seqeval-0.0.12-py3-none-any.whl size=7423 sha256=daee35553446b907223a14b39752683e00c7eb054b20db889ee0a8a82cf53272
  Stored in directory: /home/soham/.cache/pip/wheels/dc/cc/62/a3b81f92d35a80e39eb9b2a9d8b31abac54c02b21b2d466edc
Successfully built seqeval


In [4]:
# %cd '/content/drive/My Drive/IEEE BigMM/IEEE-BigMM/Code'

/content/drive/.shortcut-targets-by-id/1wOje_Q9CmqTKviMB46IyoCb-GEO1cmWw/IEEE BigMM/IEEE-BigMM/Code


In [3]:
import numpy as np
import pandas as pd
from simpletransformers.classification import ClassificationModel

In [4]:
df = pd.read_csv('clean_datav4.csv')
# df

In [5]:
text = df['text'].values.reshape(-1, 1)

In [6]:
text.shape

(7978, 1)

In [7]:
support = df['Support'].values.reshape(-1, 1)
oppose = df['Oppose'].values.reshape(-1, 1)

In [8]:
labels = np.zeros(support.shape)

In [11]:
# labels are
# 0-neutral
# 1-support
# 2-oppose

In [13]:
labels = support * 1 + oppose * 2
labels

array([[1.],
       [1.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]])

In [10]:
labels[3]#oppose

array([2.])

In [11]:
data_arr = np.concatenate((text, labels), axis=1)

In [12]:
data_arr

array([['new post domestic violence awareness caught metoo new york time published might get fit ',
        1.0],
       ['domestic violence awareness caught metoo ', 1.0],
       ['mother nature metoo ', 0.0],
       ...,
       ['wake metoo movement hairstylist sapna bhavani warned amitabhbachchan saying truth soon truth also industry gonna collapse metoo campain btown bollwood bigb sapnabhavani comeoutwomen ',
        0.0],
       ['metoo icc step sexual harassment ', 0.0],
       ['long live metoo metooindia hope culprit punished survivor get justice ',
        0.0]], dtype=object)

In [16]:
from sklearn.model_selection import train_test_split
text_train, text_test, label_train, label_test = train_test_split(text, labels, train_size=0.75, shuffle=True)

In [17]:
text_train.shape, label_train.shape

((5983, 1), (5983, 1))

In [18]:
train_df = pd.DataFrame(data=np.concatenate((text_train, label_train), axis=1), columns=['text', 'labels'], index=None)
test_df = pd.DataFrame(data=np.concatenate((text_test, label_test), axis=1), columns=['text', 'labels'], index=None)

In [19]:
np.unique(train_df['labels'], return_counts=True)

(array([0.0, 1.0, 2.0], dtype=object), array([3687, 1851,  445]))

In [20]:
np.unique(test_df['labels'], return_counts=True)


(array([0.0, 1.0, 2.0], dtype=object), array([1188,  650,  157]))

In [21]:
model = ClassificationModel('roberta', 'roberta-base', num_labels=3)

In [22]:
train_df

text labels
0     prashanth sambargi taking interesting twist sh...      1
1             right believesurviviors metoo believeher       0
2     preserve honour youtoo avoid victim metoo get ...      0
3     anu malik sexual harassment allegation sony tv...      1
4     said much metoo thankfully lucky enough never ...      0
...                                                 ...    ...
5978                   annoyed bharathiraja slam metoo       1
5979  long metoo moment black woman weighed differen...      0
5980  ad stand test time amul topical comic one long...      1
5981                                kuptaan year metoo       0
5982  offcentre anuradhasays speaks swapan55 male pe...      0

[5983 rows x 2 columns]

In [23]:
# !pip uninstall apex
# !git clone https://www.github.com/nvidia/apex
%cd apex

Cloning into 'apex'...
remote: Enumerating objects: 74, done.
remote: Counting objects: 100% (74/74), done.
remote: Compressing objects: 100% (55/55), done.
remote: Total 7329 (delta 37), reused 39 (delta 19), pack-reused 7255
Receiving objects: 100% (7329/7329), 13.88 MiB | 9.03 MiB/s, done.
Resolving deltas: 100% (4937/4937), done.
Checking out files: 100% (290/290), done.
/content/drive/.shortcut-targets-by-id/1wOje_Q9CmqTKviMB46IyoCb-GEO1cmWw/IEEE BigMM/IEEE-BigMM/Code/apex


In [24]:
%ls

apex/  docs/      LICENSE    requirements_dev.txt  setup.py
csrc/  examples/  README.md  requirements.txt      tests/


In [ ]:
# !pip install apex
!python3 setup.py install


In [26]:
model.train_model(train_df)


Selected optimization level O1:  Insert automatic casts around Pytorch functions and Tensor methods.

Defaults for this optimization level are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
Processing user overrides (additional kwargs that are not None)...
After processing overrides, optimization options are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic


Running loss: 1.068320

/usr/local/lib/python3.6/dist-packages/torch/optim/lr_scheduler.py:114: UserWarning: Seems like `optimizer.step()` has been overridden after learning rate scheduler initialization. Please, make sure to call `optimizer.step()` before `lr_scheduler.step()`. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning)


Running loss: 0.531169

/usr/local/lib/python3.6/dist-packages/torch/optim/lr_scheduler.py:231: UserWarning: To get the last learning rate computed by the scheduler, please use `get_last_lr()`.
  warnings.warn("To get the last learning rate computed by the scheduler, "


Running loss: 1.389587Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 32768.0
Running loss: 1.341466Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 16384.0
Running loss: 0.759857


/usr/local/lib/python3.6/dist-packages/torch/optim/lr_scheduler.py:200: UserWarning: Please also save or load the state of the optimzer when saving or loading the scheduler.
  warnings.warn(SAVE_STATE_WARNING, UserWarning)


In [27]:
# %ls


In [28]:
# %cd apex

In [29]:
# !python3 setup.py install

In [32]:
from sklearn.metrics import f1_score, accuracy_score


def f1_multiclass(labels, preds):
    return f1_score(labels, preds, average='micro')
    
result, model_outputs, wrong_predictions = model.eval_model(test_df, f1=f1_multiclass, acc=accuracy_score)

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:900: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)


In [33]:
result, model_outputs, wrong_predictions = model.eval_model(test_df)

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:900: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)


In [37]:
result, model_outputs, wrong_predictions =model.eval_model(test_df)

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:900: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)


In [41]:
model.predict(['metoo is wrong!!'])

(array([0]), array([[ 1.0283203 ,  0.32739258, -1.5673828 ]], dtype=float32))